export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR'
export const EDIT_SNACKBAR_TEXT = 'EDIT_SNACKBAR_TEXT'
export const EDIT_SNACKBAR_BET_ID = 'EDIT_SNACKBAR_BET_ID'
